### ISSUE TITLE
tk install for ML modules?

### ISSUE THREAD

**Issue by svallero** [alidock/alidock#100]
Would it be possible to yum install tk-devel which is needed by ML modules at runtime?

**Comment by mconcas** [comment]
Hi @svallero ,
Did you try: `alidock root` and `yum install tk-devel` already?

**Comment by svallero** [comment]
Ciao,
yes and it works fine. The idea is to have the ML framework run smoothly on Alidock using the Alibuild system, without asking the user to install stuff. 
Or one should also use a recipe for system libs?

**Comment by mconcas** [comment]
Ok, I see what you mean.

The base image used for alidock is the same used for the CI, plus few amenities to make it usable by humans.
I think (@dberzano can confirm) that the best solution is to keep it 'as it is' .
As we saw in the past it happens that alibuild packages can mess up with system/alternative installations of the same package.
Indeed, you could also write a recipe for aliBuild (!!), but I think maybe would be easier to prepare another image based on alisw/alidock and add the needed system libraries. 
(e.g. In my case I work with: `alidock [--nvidia] --image mconcas/alicuda`)

**Comment by mconcas** [comment]
Hi @svallero, 
Wrapping it up:
- We would like to keep the base image as is, for general purpose cases
- Nevertheless people are encouraged to develop their own images, based on the alisw/alidock one
- Possibly we are evaluating the idea to open :soon: :tm: another repository to host _essentials_, that is community supported Dockerfiles, with automatic image publication on some registry (most likely on DockerHub), standard and custom tests, and all those fancy things

Closing.
