### ISSUE TITLE
Fix red tests: PyLint 2.3.1

### ISSUE THREAD

**Issue by mconcas** [alidock/alidock#105]
New pull requests started to fail, due to the PyLint test.

Last time it succeeded: 
 - PyLint version: 2.2.2 #99 see also [travis](https://travis-ci.com/dberzano/alidock/jobs/180087009)

First time it failed:
 - PyLint version: 2.3.1 #91 see also [travis](https://travis-ci.com/dberzano/alidock/jobs/183080988)

[PyLint changelog](http://pylint.pycqa.org/en/stable/whatsnew/changelog.html)

[UPDATE] have a look [here](https://github.com/PyCQA/pylint/issues/2605#issuecomment-441456179)

**Comment by dberzano** [comment]
It has to be noted that #91 has pylint 1.9.4 in the Python 2.7 test. Also, PyCQA/pylint#2605 refers to an issue with pylint 2.1.1. Still, as discussed today, I think we're right saying this is a pylint "bug".

**Comment by dberzano** [comment]
OK here's a short reproducer:

```python
"""Reproducer."""

def fun():
    """Description."""
    try:
        pass
    except Exception as exc:
        raise exc
    try:
        pass
    except OSError as exc:
        if exc.errno == 42:
            pass
```

Works with pylint 2.2.3. Breaks with pylint 2.3.0, with error:

```
test.py:12:11: E1101: Instance of 'Exception' has no 'errno' member (no-member)
```

It tracks the life of the `exc` variable. It sees it's an `Exception`, and, in spite of it becoming an `OSError` later, the check still thinks it's the former type and complains about the missing member.
