### ISSUE TITLE
Enable named configuration sets

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#117]
Have sections in config file. This would enable switching between containers by simply using the `--name` switch.

**Comment by mconcas** [comment]
We must take into account that:
1.  maybe the `--name` parameter is not the best, think about the difference between a container image and the container instance.
If I launch something custom, let's say: `alidock --cvmfs --nvidia --rocm --name <name> --image <image>`. It would add an entry in the configuration file that stores my config parameters under the key `<name>`.
What if I stop the container? Am I supposed to remove the entry from the configuration?. What if the container dies _spontaneously_ not under the alidock control?
I think that we still need to distinguish that bookkeeping != configruration
2.  As we discussed we also need to keep a default behaviour, that means at some point to assign label to a _default_ one

Just brainstorming, will add more lines as they come to my mind. This is a critical point, as you well know.

**Comment by dberzano** [comment]
Config must be backwards-compatible. So whatever we have in current config, is the "default". Named configurations can go in a separate toplevel key (this is so Kubernetes).

For instance:

```yaml
---
cvmfs: True
nvidia: False
profiles:
  alirocm:
    nvidia: False
    cvmfs: False
    dontUpdateImage: True
```

Now the default part will correspond to `--name alidock`. We should obviously remove the ability to specify the container name through `dockName` though.
