### ISSUE TITLE
No network inside alidock

### ISSUE THREAD

**Issue by pkurash** [alidock/alidock#136]
Hello, 

I can not access network from the alidock:

[alidock] ~ $> ping www.cern.ch
ping: www.cern.ch: Name or service not known

The same with ssh and alien-token-init commands.

The /etc/resolv.conf file inside the docker is different from that of the host system:

> [alidock] ~ $> cat /etc/resolv.conf 
># Use cloudflared
>nameserver `127.0.0.1`

I tried to edit this and some other configuration files but the network is still not accessible and the edited content is obliterated after I restart docker.service.

>uname -a (host system)
>Linux sabayon.local 5.0.0-sabayon #1 SMP Sat Jun 1 21:26:32 UTC 2019 x86_64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz GenuineIntel GNU/Linux

My alidock version is 1.4.0.

Other related command outputs:
[alidock.log](https://github.com/alidock/alidock/files/3271800/alidock.log)
[docker.log](https://github.com/alidock/alidock/files/3271810/docker.log)

Best regards,
Podist

**Comment by mconcas** [comment]
Hello @pkurash,
that custom configuration in the `resolv.conf` is indeed created at the container startup, to ensure fixing some DNS misconfiguration in your docker installation. It essentially performs a test on your container connection and defaults to a cloudflared-based solution in case it cannot resolve the www.google.com address.

So, it either looks like you are offline or inside a network that does not allow you to resolve the cern website, for instance.

I am hereafter assuming then that you are able to reach the www.cern.ch website from your browser. You could try a few things to help me to figure it out what's wrong:

1. run `alidock stop && alidock` and test again, once you are sure to be connected to the internet.
2. if it does not work, you can manually test your docker containers' connection by running something like: `docker run -it --rm ubuntu:latest bash` and then try to access the www.cern.ch website with: `apt update && apt-get install -y curl && curl www.cern.ch` and post the result.

Cheers,
Matteo

**Comment by pkurash** [comment]
Hello Matteo,

Thank you for your answer.

All sites of interest are accessible from my network, I am able to connect to CERN and submit my commits to GitHub.
Please find the outputs of the suggested commands in the attachments:
[1.txt](https://github.com/alidock/alidock/files/3277777/1.txt)
[2.txt](https://github.com/alidock/alidock/files/3277778/2.txt)

Best regards,
Podist

**Comment by mconcas** [comment]
Hello @pkurash , sorry for late reply.
Well, good news is that it is apparently not an alidock bug.
Bad news is that most likely your docker installation is missing something.

Assuming you are admin of the machine you are using, to better understand what might be the cause of your problem, I need to know few more details:

1. are you in a network with its own DNS server? Can you please report me the `cat /etc/resolv.conf` of your local host?
2. can you please do the same with a container, for instance: `docker run ubuntu:latest cat /etc/resolv.conf`

Cheers,
Matteo

**Comment by pkurash** [comment]
Good afternoon,

Surprisingly enough the contents of /etc/resolv.conf file inside docker is the same as that of the system:

```$  cat /etc/resolv.conf
# Generated by NetworkManager
search local
nameserver 31.11.202.254
nameserver 37.8.214.2

 $ docker run ubuntu:latest cat /etc/resolv.conf
# Generated by NetworkManager
search local
nameserver 31.11.202.254
nameserver 37.8.214.2
```

But the command apt update still is still failing. 

The computer is connected to the router of a home network with the same DNS at in the second line of the conf file and it has been working fine before. I also tried other networks but it did not work.

I have installed docker from my system package repository.  The current version is 18.09.5.

Regards,
Podist.

**Comment by mconcas** [comment]
Good afternoon,
ok, not really a surprise, since Docker usually copies the resolv.conf on the host to the containers. It means it is working correctly. In alidock you see the different resolv.conf because of the adoption of cloudflare to address issues with name resolution, but usally you would see the same resolv.conf.

My suspects are now directed on the docker installation on a Gentoo-based OS. There could be something missing in the bridging and/or IP forwarding rules.

Could you please post the content  `/etc/systemd/network/50-static.network`?

To be fair, I am not an expert in Gentoo-flavoured distros, I am trying to follow what i found in these links, if you want to have a look too:
 - [1](https://wiki.gentoo.org/wiki/Docker#systemd-networkd)
 - [2](https://forums.gentoo.org/viewtopic-t-1058284-start-0.html)

Regards

**Comment by pkurash** [comment]
Hello again,

After studying the docker documentation and much googling I encountered the following [solution](https://stackoverflow.com/questions/51752597/docker-container-can-t-connect-to-internet): insert option '-net=host' so the full command is: 

`docker run -it --net=host --rm ubuntu:latest bash `

which is working for me and now I am able to connect to fetch updates inside the Ubuntu container.

What is the best way to pass this extra argument to alidock?

Best regards,
Podist

**Comment by mconcas** [comment]
Hello,

it is not possible and will likely not be in the foreseeable future to make alidock containers to share the network stack with the host (that is what  `--net=host` does, and it's not recommended for security reasons).

Docker needs to be allowed to have IP forwarding configured properly, in order to make its private networks and virtual network interface to access the internet in a canonical way.

If you agree we can try to fix your docker installation on Gentoo.

> Could you please post the content of `/etc/systemd/network/50-static.network`?

Regards,
Matteo

**Comment by pkurash** [comment]
Hello,

The file /etc/systemd/network/50-static.network was not present by default, I activated systemd-networkd and created the file it by hand as explained [here](https://wiki.gentoo.org/wiki/Docker#systemd-networkd):

```$ cat /etc/systemd/network/50-static.network 
[Match]
Name=enp6s0

[Network]
DHCP=yes
IPForward=true
IPMasquarade=true
```
I also attach the contents of ifconfig command
[ifconfig.log](https://github.com/alidock/alidock/files/3309715/ifconfig.log)

Regards,
Podist

**Comment by mconcas** [comment]
Ok, let's try to edit it in order to match the wireless network interface you are using:
change the `enp6s0`  into `wlp2s0`
then give:
`systemctl daemon-reload`
then restart the docker daemon:
`systemctl restart docker` or `service docker restart`

and see if now it works.
Regards,
Matteo

**Comment by pkurash** [comment]
Unfortunately it did not work.

Please also find the outpus of the commands:
```$ networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 enp1s0           ether              no-carrier  unmanaged 
  3 wlp2s0           wlan               routable    unmanaged 
  5 docker0          bridge             routable    unmanaged 
 19 vethce444b4      ether              degraded    unmanaged 

5 links listed.
```
and
`sysctl -a | grep -i net` (attachment)

[systctl.log](https://github.com/alidock/alidock/files/3309930/systctl.log)

Is something wrong in it?

Best regards,
Podist

**Comment by dberzano** [comment]
Hi @pkurash, is there any update on this? We're kindly helping, but this is really a Docker/Sabayon configuration problem, which has little to do with alidock. We'd like to see if we can fix it together 🙂

**Comment by pkurash** [comment]
Hello Dario,

I installed fresh Sabayon image on a virtual machine, the alidock worked fine from the beginning but after docker and systemd updates it resulted at the same trouble. 

As I concluded this is a bridge problem which needs a special fix on my system. 

I addressed the docker people opening a topic on the forum asking for help, hope they will help me to find the reason.

Regards,
Podist

**Comment by dberzano** [comment]
Good to hear that! Do you think we can close the ticket? Thanks!

**Comment by pkurash** [comment]
OK, we can close close the ticket for now.
Regards,
Podist
