### ISSUE TITLE
automatically discover host cvmfs

### ISSUE THREAD

**Issue by adriansev** [alidock/alidock#140]
Would be great if the building step within container can be skipped by the usage of host cvmfs.
alidock could gain argument(s) that would be be passed to alienv inside the container for loading cvmfs packages

**Comment by mconcas** [comment]
Hi @adriansev , alidock has already the `--cvmfs` flag to expose CVMFS inside. 
Plus, if you use the default build cc7-base, you can already benefit of pre-compiled packages to be downloaded (alibuild's merit). I might be missing your point but I think it is not really related to alidock itself.
Feel free to re-open the issue, in case I am wrong.
