### ISSUE TITLE
Error while trying to use/install alidock: Warning: Identity file /home/emil/alidock/.alidock-ssh/alidock.pem not accessible: No such file or directory.

### ISSUE THREAD

**Issue by EmilGorm** [alidock/alidock#144]
Hi,

I have installed docker on my laptop, and it runs successfully.
I then installed alidock using

> bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)

which also seems to run. But when i try to run alidock afterwards I get an error

> alidock
  Starting a shell into the container
  Warning: Identity file /home/emil/alidock/.alidock-ssh/alidock.pem not accessible: No such file 
  or directory

I have linked the .globus directory in ~ with ~/alidock/.globus and both have CERN userkey.pem and usercert.pem

I am running Ubuntu 18.04 and docker 19.03.2

Hope you can help,
Emil Gorm

**Comment by dberzano** [comment]
Hello Emil, the error is unrelated to your Grid certificate. Can you please do:

```
ls -l ~/alidock/.alidock-ssh/alidock.pem
ls -l ~/alidock
```

so that we can verify the permissions?

I'd say a possible solution is to completely remove the `~/alidock` directory (assuming you have nothing important inside):

```
rm -rf ~/alidock/
```

then install alidock:

```
bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)
```

then follow [this guide](https://alice-doc.github.io/alice-analysis-tutorial/start/cert.html) for obtaining and storing the certificate in a way that it is accessible both from inside and outside alidock.

**Comment by EmilGorm** [comment]
Hi,
When doing 

> ls -l ~/alidock
 total 0
> ls -la ~/alidock
 total 12
drwxr-xr-x  2 emil docker 4096 Sep 26 13:33 .
drwxr-xr-x 35 emil emil   4096 Sep 26 13:33 ..
-rw-r--r--  1 emil docker   10 Sep 26 13:33 .alidock_pip_check

I have already tried removing an reinstalling alidock with the same results

**Comment by dberzano** [comment]
Hi, let's try then with:

```
ls -ld ~/alidock
```

Can you also attach the `~/alidock/.alidock-host.log` file?

**Comment by EmilGorm** [comment]
I get

> ls -ld ~/alidock/
drwxr-xr-x 2 emil docker 4096 Sep 26 14:23 /home/emil/alidock/

There is no .alidock-host.log file. The only file in the ~/alidock/ repository seems to be .alidock_pip_check

**Comment by dberzano** [comment]
OK, so I have started a fresh Ubuntu 18.04 installation, [installed Docker 19.03.2](https://docs.docker.com/install/linux/docker-ce/ubuntu/), installed alidock using the one-liner above, and I cannot reproduce your problem at all. It just works perfectly as expected.

What happens in your case is that alidock does not write the required startup files inside the `~/alidock` directory.

Do you have, by chance, a `~/.alidock-config.yaml` file? (If it's not there, do not create one.)

Can you please reinstall, and post the full output of the installation command?

```
bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)
```

You should have Python 3 on your system, does it come from the standard Ubuntu distribution? Or, did you install it via Conda or similar? Please do:

```
type python3
```

Do you have anything "special" in your environment (`~/.bashrc`), as in sourcing other scripts or exporting custom variables?

**Comment by dberzano** [comment]
Please also post the output of `docker ps`.

**Comment by EmilGorm** [comment]
Hi,

I did a completely fresh install of docker, alidock and all prerequisites and it fixed the issue.
Must have been something with docker even though it ran.

Thank you for your time

**Comment by dberzano** [comment]
Very good, thanks!
