### ISSUE TITLE
 Alidock stucked on "Creating container, hold on '' for several hours

### ISSUE THREAD

**Issue by spadhan** [alidock/alidock#154]
I have alidock version 1.5.3 and docker version  19.03.12
macOS Mojave version 10.14.6
python3 version- Python 3.8.5
python version -Python 2.7.16

**Comment by ShiQiu1** [comment]
Hi, I had the same issue today. But when I kept trying it, somehow it worked suddenly. I think that alidock is trying to download something and gets stuck on that. In Linux, there is a syslog file located at /var/log/syslog which stores the info of system processes. Maybe there is a similar log file in macOS. 

Once alidock successfully created container, I have following lines in syslog file:

> Aug 28 14:50:16 "MYUSERNAME" kernel: [ 3329.874530] docker0: port 1(veth92e440f) entered blocking state
> Aug 28 14:50:16 "MYUSERNAME" kernel: [ 3329.874535] docker0: port 1(veth92e440f) entered forwarding state
> Aug 28 14:50:16 "MYUSERNAME" NetworkManager[768]: <info>  [1598619016.6599] device (veth92e440f): carrier: link connected
> Aug 28 14:50:16 "MYUSERNAME" NetworkManager[768]: <info>  [1598619016.6608] device (docker0): carrier: link connected

Before it succeeded, I killed the process as alidock froze. In syslog, it says:

> Aug 28 14:02:00 "MYUSERNAME" dockerd[1391]: time="2020-08-28T14:02:00.166596402+02:00" level=error msg="Not continuing with pull after error: context canceled"

From the message, it seems that alidock needs to pull something. Maybe you could check your syslog to see why it stuck.

**Comment by mconcas** [comment]
Hello, yes, alidock 1.5.3 now downloads an updated container, which might take a while, especially with poor connection.
The uncompressed image is around 2.5GB.

**Comment by spadhan** [comment]
Does it take some time to create a container after typing alidock?

**Comment by mconcas** [comment]
> Does it take some time to create a container after typing alidock?

usually very little if the container image has been downloaded already, otherwise it depends on your connectivity.
Could you please be so kind to try in your terminal:
```bash
docker pull alisw/alidock
```
This is basically the command that runs hiddenly with alidock. 
The output might help us to understand whether you succeded in downloading the image already or you got stuck because of the pulling duration.

Let me know what happens and thanks for your help.

**Comment by spadhan** [comment]
Now I can start alidock . but after typing ali I got this error

ERROR: AliPhysics/latest was not found

**Comment by mconcas** [comment]
> Now I can start alidock . but after typing ali I got this error
> 
> ERROR: AliPhysics/latest was not found

Have you tried to rebuild AliPhysics?

**Comment by spadhan** [comment]
No. I did not try.

**Comment by spadhan** [comment]
Before this issue, when I type ali after alidock command, it redirects automatically to  aliroot page.

**Comment by mconcas** [comment]
> Before this issue, when I type ali after alidock command, it redirects automatically to aliroot page.

The `ali` command not working is however not related to alidock but more related to the availability of the `AliPhysics/latest` name in your builds.
What does `type ali` return?

**Comment by spadhan** [comment]
ERROR: AliPhysics/latest was not found

**Comment by mconcas** [comment]
That is the output of the `ali` command, which should probably be an alias.
Try to rebuild your AliPhysics and that should work.

closing this issue, becaus it is anyways not related to alidock itself.
