### ISSUE TITLE
problems with alidock installation

### ISSUE THREAD

**Issue by pchrista** [alidock/alidock#155]
hi,

my alidock installation that used to work w/o problems, does not work anymore (due to some automatic system update?).
I removed $HOME/.virtualenvs/alidock/ and reinstalled alidock with 
bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)

This command gave the attached output, which as far as I understand shows that things are missing.
Is there maybe any conflict with the current python version my system has?
Any suggestion would be appreciated!

Greetings,
Panos

ps: OS Catalina (10.15.6)
<img width="1014" alt="alidock-output" src="https://user-images.githubusercontent.com/28891346/91665807-96bd5180-eaf8-11ea-81a6-3dd5be04c165.png">

**Comment by pchrista** [comment]
Hi all,
is there maybe any suggestion?
I see that I did not specify before the following

docker 2.3.0.4 on Catalina (10.15.6)
python 2.7.16 and python3 3.8.2

**Comment by mconcas** [comment]
From the output it looks you are installing alidock with Python 3.8+.
I am not sure but this could be the issue.
On my Mac i have python 3.7, and it works smoothly.

Have you the possibility to try with something lesser than python 3.8?
It is still quite strange, anyways.

I'll try to reproduce your issue.

**Comment by pchrista** [comment]
just an update
downscaling to 3.7.8 allows the installation to go fully through

**Comment by mconcas** [comment]
So this means that python 3.8 might break something. I'll take it into account. 
Thanks, glade you have fixed.
