### ISSUE TITLE
Move to a newer version of git

### ISSUE THREAD

**Issue by ktf** [alidock/alidock#157]
If alidock moves to a newer version of git, e.g. something along the lines of:

```bash
yum install -y rh-git218
scl enable rh-git218 bash
```

you would take advantage of the new (1.6.2) alibuild feature which uses `--filter blob:none` for the git clone. This greatly reduces the amount of sources downloaded:

```
Full O2 checkout: 2:29.01 total
693M    sw
```

**Comment by mconcas** [comment]
I see the slc7-builder image has been updated [already](https://github.com/alisw/docks/commit/c81ba7b2a3f731e206ff3bb64da823ee18bdfdd7#diff-cc99dc18b3805c9b0ce62dbbd20d29adR52) (one month ago).
So this should come for free by triggering the build for alidock container, I am doing it right now.

Thanks for the hint!
