### ISSUE TITLE
Trying to build aliPhysics I get an error

### ISSUE THREAD

**Issue by Nikolajal** [alidock/alidock#159]
When building the packages I get these error messages:
ERROR: GET https://alicache.cern.ch//TARS/slc7_x86-64/store/b2/b26492899c1e2d33f37764947e600564531ea2cb/ failed: HTTPSConnectionPool(host='alicache.cern.ch', port=443): Read timed out. (read timeout=15)
WARNING: defaults-release (b26492899c1e2d33f37764947e600564531ea2cb) not fetched: have you tried updating the recipes?

**Comment by mconcas** [comment]
Hi, this error is due to the malfunctioning of cache servers.
You can pass the `--always-prefer-system` to aliBuild command to avoid downloading precompiled builds.

It is anyways not directly related to alidock, closing.
