### ISSUE TITLE
Please update alidock to use alibuild 1.6.4

### ISSUE THREAD

**Issue by ktf** [alidock/alidock#164]
I've just released alibuild `v1.6.4` which adds support for a S3 based repository, rather than the soon to be deprecated alicache. Can you please make sure the alidock image is update to use it? No other changes WRT v1.6.3.

**Comment by mconcas** [comment]
Hi @ktf, thanks a lot for the S3 new cache and for the ping on the update.
https://github.com/alidock/alipier/pull/22 is bumping it.
