### ISSUE TITLE
/usr/bin/env: python3: No such file or directory

### ISSUE THREAD

**Issue by trancien** [alidock/alidock#168]
Hello,

I installed alidock under MacOS catalina 10.15 last week and after resolving some issues i was able to run it.
So i started to follow the analysis tutorial exercise from the ali-doc git hub :
https://alice-doc.github.io/alice-analysis-tutorial/analysis/setup.html#trouble-

But when i try to enter the alice environment shell i get the following :
[AliPhysics/latest] ~ $> alien.py
/usr/bin/env: python3: No such file or directory
or
[AliPhysics/latest] ~ $> alien-token-init
/usr/bin/env: python3: No such file or directory

Python 3 is installed on my mac and i tried to instal it on the Alienv with the same way but it didn't work.

So i try to install homebrew and even if it says that the installation was successful the last line says : /bin/bash: line 1: /usr/bin/sudo: No such file or directory
and when i try to use brew i get : -bash: brew: command not found

Can you help me please ?

Best regard,

**Comment by mconcas** [comment]
Hello,
it looks like you have some problems with your installation of aliphysics, which unfortunately is not something I can help you too much here.
Only advice I feel to give to you is that being inside the alidock docker container or on your mac are two things technically different. You will not find any `brew/sudo/python3` that are on your mac inside the container. It is a completely isolated environment. Trying to install them on the mac and expecting to find them on the container will not work.

My suggestion is, if you are not too much familiar with the concept of containers, to opt for an installation directly on your macOS machine, without using alidock, that in this case can just add further complexity to your setup.

This is of course true only if you don't have strong reasons to use alidock.

Best regards.
