### ISSUE TITLE
Problem when installing (starting) alidock on Mac OSX Catalina

### ISSUE THREAD

**Issue by nicolazurlo** [alidock/alidock#180]
I installed Docker 3.1.0
checked the disk image is .raw
checked that the filesystem is APFS

the line:
bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh).    
works well, it says
Checking if your Docker installation works
Creating an environment for alidock using Python 3.9.1 (python3)
Installing alidock under /Users/nicolazurlo/.virtualenvs/alidock
Installed: alidock 1.6.0

the command 
alidock 
doesn't succeed, it says:

Cannot communicate to Docker, is it running? Full error: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

Any hint?
Thank you in advance
Nicola

**Comment by mconcas** [comment]
Hi, can you try to install python 3.8 via brew and reinstalling alidock after?

To uninstall just remove the ~/.virtualenvs/alidock directory

**Comment by nicolazurlo** [comment]
Thanks for your support.

I did it, the output has changed but it hasn't fixed the issue:

bash-3.2$ bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)
Checking if your Docker installation works
Creating an environment for alidock using Python 3.8.7 (python3)
Installing alidock under /Users/nicolazurlo/.virtualenvs/alidock
Installed: alidock 1.6.0
You can use alidock by simply typing:
    alidock
bash-3.2$ alidock
Creating container, hold on
Starting a shell into the container
Cannot continue: cannot log into the container, maybe it did not start up properly: check log file /Users/nicolazurlo/alidock/.alidock-alidock/log.txt for details and make sure your Docker version is updated. Error: 404 Client Error for http+docker://localhost/v1.41/containers/alidock-501/json: Not Found ("No such container: alidock-501")

And here I copy&paste the file /Users/nicolazurlo/alidock/.alidock-alidock/log.tx
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 63158 ssh2: RSA SHA256:6GmEKXF4qu3D9gN49hb9UHqT6Cxab/aR1yttYrPgmXs
Setting tty modes failed: Invalid argument
Received signal 15; terminating.
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 61422 ssh2: RSA SHA256:SnTDT8+nrjvftle8XO9okbrwHrAR+xCA81Q+6l1BXt4
Setting tty modes failed: Invalid argument
Setting tty modes failed: Invalid argument
Setting tty modes failed: Invalid argument
Setting tty modes failed: Invalid argument
Setting tty modes failed: Invalid argument
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 63734 ssh2: RSA SHA256:y2XXPDrc+oa7ch7F88PhHAv7Nnsx701h//M2gOHy09g
Setting tty modes failed: Invalid argument
Received signal 15; terminating.
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 58318 ssh2: RSA SHA256:QLZTbskxnj4z77anYl1DGEULrtE4zIWrRXPKxushjJ4
Setting tty modes failed: Invalid argument
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 58334 ssh2: RSA SHA256:HpYtdeAMBkxQ3WETbnl3Nkd70Lawt207KQPPwXuO7UE
Setting tty modes failed: Invalid argument
Received signal 15; terminating.
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 58236 ssh2: RSA SHA256:YLzV5zywH6A4bgSQ9+gINM6T9iXgzOzd0FT7b7iiMdA
Setting tty modes failed: Invalid argument
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted publickey for root from 172.17.0.1 port 58010 ssh2: RSA SHA256:IW70kxW/jwUq3yUbyuz5aw7G0TN+A6iELJbveq1HNrc
Setting tty modes failed: Invalid argument

Any other suggestions?

PS. I rerun alidock again and I got the same error message as with Python 3.9.1 
bash-3.2$ alidock
Creating container, hold on
Cannot communicate to Docker, is it running? Full error: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

Not clear what has changed between the first and the second trial... apparently nothing.
