### ISSUE TITLE
memlock cannot be resized

### ISSUE THREAD

**Issue by JianLIUhep** [alidock/alidock#181]
Dear experts,

Is there a way in alidock to resize the memlock? 
For my understanding, it can be easily resized by modifying /etc//security/limits.conf out of docker, and can be changed by adding arguments like _docker run --ulimit_ in docker. But I have no idea how to set the value with alidock. 

Thank you in advance.

Best regards,
Jian

**Comment by mconcas** [comment]
Hi,
It is not possible in alidock.

**Comment by JianLIUhep** [comment]
Thanks a lot for the quick answer. I am going to close this ticket.
