### ISSUE TITLE
tmux -CC makes session to hang

### ISSUE THREAD

**Issue by mconcas** [alidock/alidock#22]
It turns out that if you ask for a `tmux -CC` session in a terminal that does not support tmux integration, it more or less silently (it depends on the terminal app you use) hangs in errors.

Step to reproduce the bug:
option 1) Use builtin Term.app on macos
option 2) Use any other terminal on Linux

Since, after a quick lookup on the stackoverflow bible, it looks like `-CC` is officially supported only on iTerm*. Therefore, I would adjust the option _ad hoc_.

See PR.

Cheers

**Comment by dberzano** [comment]
`man tmux` does not say anything iTerm-specific in the `CONTROL MODE` section, but thanks for raising the issue, which stands.
