### ISSUE TITLE
Expose additional directories in the container

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#64]
One of alidock's driving principles is that there is a single working directory made visible to your container:

    ~/alidock -> /home/alidock

Even though data should be moved to that directory in order to make it visible, there are cases in which this is not feasible - for instance, when data is on one or more external disks.

Directory exposure should be implemented by preventing users from doing mistakes with their own Docker installation.

The proposal is to allow users to provide multiple directories that will be mounted inside the container. Command line:

```bash
alidock -v /my/dir -v /opt/foo -v /tmp/bar -v /opt/bar
```

Configuration file (preferred):

```yaml
---
volumes:
  - /my/dir
  - /opt/foo
  - /tmp/bar
  - /opt/bar
```

alidock will check if they are directories and prevent users from bind-mounting files. If they are symlinks, they are resolved before this check. All directories will be mounted in a flat space, and name clashing is resolved by respecting the order and incrementing a counter:

```
/mnt/dir
/mnt/foo
/mnt/bar
/mnt/bar2
```

**No nested mounting is allowed** since Docker has problems dealing with it. All mount points will be exported in `rw` mode by default.

This would solve #52 as well.

The only special case would be `/cvmfs`, mounted under `/cvmfs` directly (not under `/mnt/cvmfs`), and with mount propagation policy `shared` (in order to make `autofs` work), but only on systems that support it (hence, not macOS).

Of course this is just a proposal, so any comment/objection is welcome.

**Comment by rhaake** [comment]
Hi Dario,
  This sounds very good and would allow me to use alidock.
Best,
Ruediger

**Comment by mconcas** [comment]
> All directories will be mounted in a flat space, and name clashing is resolved by respecting the order and incrementing a counter:

I'd prefer, even if it's not very good to see, something that leaves no space to ambiguities, say there are /a/b/c and /e/f/c (I know, is bad looking forl long pathnames 👎):
```bash
/a/b/c -> /mnt/a.b.c ||  /mnt/a_b_c
/e/f/c -> /mnt/e.f.c || /mnt/e_f_c
```

> alidock will check if they are directories and **prevent users from bind-mounting files**.

Agree.

> The proposal is to allow users to provide multiple directories that will be mounted inside the container. Command line:\
`alidock -v /my/dir -v /opt/foo -v /tmp/bar -v /opt/bar`

I would not call them volumes, since this messes with the docker syntax, I will stick with the `--expose` option, also for configuration file. What about passing the volumes as a list requiring at least 1 argument?
```
alidock --expose /a/b/c  /d/e/f
```

>The only special case would be /cvmfs, mounted under /cvmfs directly (not under /mnt/cvmfs), and with mount propagation policy shared (in order to make autofs work), but only on systems that support it (hence, not macOS).

That's why I would optfor a `--cvmfs` specific flag

**Comment by dberzano** [comment]
> I would not call them volumes, since this messes with the docker syntax

I would call them volumes for exactly this reason :-) Note that `expose` conflicts with the Docker concept of "exposing" ports. Do we have a third name option that makes everyone happy? 😄 

Having the full directory path unwinded is something I consider ugly. I'd stick with my first proposal with some amendments: you can optionally specify the mount label (not path, ever) yourself with:

```yaml
volumes:
  - /my/dir
  - /opt/foo
  - /tmp/bar
  - /opt/bar:another_bar  # <-- this
```

and if you have a conflict without specifying the label, it stops with an error.

`--cvmfs` flag: agreed. It's a special case, it deserves a special option.

Any thought?

**Comment by dberzano** [comment]
OK, there's convergency of `--mount` as the option, and on adding an extra option to mount the thing in read-only mode (not the default).

The symlink issue: Docker does exactly the right thing. If you mount a symlink to a dir, it's visible as a dir inside. So, no check needed.

**Comment by dberzano** [comment]
`~/.alidock-config.yaml`. Write something like:

```yaml
---
mount:
  - "~/Dropbox"
  - "~/cernbox"
```
