### ISSUE TITLE
alidock on CentOS

### ISSUE THREAD

**Issue by tariqmahmoud** [alidock/alidock#65]
1) I installed docker on my centos machine (CentOS Linux release 7.6.1810)

 2) I installed alidock via:
bash <(curl -fsSL https://bit.ly/alidock-installer)

3) running alidock: --> error message:
     Creating container, hold on
     Starting a shell into the container
     Cannot continue: cannot find container, maybe it did not start up properly: check log file ~/alidock/.alidock.log for details. Error: '22/tcp'

It looks like if alidock is not able to cennect to the container that it creates! right?
typing docker ps shows nothing!!

4) Testing docker:
    docker run hello-world
    docker run -it ubuntu bash

it worked as expected. I also see the ubuntu container listed:

docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
497a7c1d4563        ubuntu              "bash"              36 seconds ago      Up 34 seconds                           stupefied_kare

Is there any idea what is going on? Does alidock try to open port 22? how can I make port 22 accessible for alidock?

**Comment by mconcas** [comment]
Hi @tariqmahmoud,

Thanks for your feedback.
Indeed it is weird.
Can you please either attach or link a reference to the logfile: `~/alidock/.alidock.log` ?

Cheers,
Matteo Concas

**Comment by tariqmahmoud** [comment]
sorry. have forgotten to mention, that i do not find the file!!!! it simply does not exist. That was the first thing i tried.

**Comment by dberzano** [comment]
Please do:

```bash
docker ps | grep alidock
ls -ld ~/alidock
ls -ld ~/alidock/.*
```

and attach the results. Please also run:

```bash
docker --version
```

and make sure it's at least 18.

**Comment by tariqmahmoud** [comment]
[mahmoud@madonna ~]$ docker ps | grep alidock
[mahmoud@madonna ~]$ ls -ld ~/alidock
drwxr-xr-x 2 mahmoud users 144 Dec 12 15:40 /home/mahmoud/alidock
[mahmoud@madonna ~]$ ls -ld ~/alidock/.*
drwxr-xr-x  2 mahmoud users  144 Dec 12 15:40 /home/mahmoud/alidock/.
drwxr-xr-x 49 mahmoud users 4096 Dec 12 13:26 /home/mahmoud/alidock/..
-rw-r--r--  1 mahmoud users   10 Dec 12 15:14 /home/mahmoud/alidock/.alidock_docker_check
-rw-r--r--  1 mahmoud users    7 Dec 12 15:43 /home/mahmoud/alidock/.alidock-host.log
-rwx------  1 mahmoud users  262 Dec 12 15:43 /home/mahmoud/alidock/.alidock-init-host.sh
-rwx------  1 mahmoud users 4287 Dec 12 15:43 /home/mahmoud/alidock/.alidock-init.sh
-rw-r--r--  1 mahmoud users   10 Dec 12 15:14 /home/mahmoud/alidock/.alidock_pip_check
[mahmoud@madonna ~]$ docker --version
Docker version 18.09.0, build 4d60db4
#######################
alidock-host.log:
[.alidock-host.log](https://github.com/dberzano/alidock/files/2675400/default.alidock-host.log)

**Comment by dberzano** [comment]
Hi Tariq, can you try to run the container manually and report what happens? Just copy-paste the following:

```bash
docker run -it --cap-add SYS_PTRACE --hostname alidock-$UID --name alidock-$UID -p 22 -v $HOME/alidock:/home/alidock:rw alisw/alidock /home/alidock/.alidock-init.sh
```

In a different shell, run afterwards:

```bash
docker inspect alidock-$UID
```

and send us the output.

Thanks, cheers

**Comment by tariqmahmoud** [comment]
first:
[mahmoud@madonna ~]$ docker run -it --rm --cap-add SYS_PTRACE --hostname alidock-$UID --name alidock-$UID -p 22 -v $HOME/alidock:/home/alidock:rw alisw/alidock /home/alidock/.alidock-init.sh
/usr/local/bin/entrypoint.sh: line 4: /home/alidock/.alidock-init.sh: Permission denied
/usr/local/bin/entrypoint.sh: line 4: exec: /home/alidock/.alidock-init.sh: cannot execute: Permission denied
[mahmoud@madonna ~]$ 


second:

[mahmoud@madonna ~]$ docker inspect alidock-$UID
[ ]
Error: No such object: alidock-2142
[mahmoud@madonna ~]$

**Comment by mconcas** [comment]
Hi @tariqmahmoud ,
ok, there are some possibilities that come to my mind:

1) You don't have the `$HOME/alidock` directory
2) You don't have the right permissions on your `$HOME/alidock` (sub-)directories

Can you please check if you are in one of these two cases?

**Comment by dberzano** [comment]
In addition to what @mconcas said, let me add: are you on your own computer? That user ID (2142) seems pretty high, you may be on a shared installation. The offending script _is_ executable by you:

```bash
-rwx------ 1 mahmoud users 4287 Dec 12 15:43 /home/mahmoud/alidock/.alidock-init.sh
```

Can you run the following command and post us the output?

```bash
id
```

Can you please also tell us if your `$HOME` is mounted on a local filesystem, or a shared one (such as a network filesystem?)

What's the value of `$HOME`?

What's the output of `mount`?

**Comment by tariqmahmoud** [comment]
thanks. I am in a network file-system. Here are the outputs of id $HOME and mount:     

[mahmoud@madonna ~]$ id
uid=2142(mahmoud) gid=100(users) groups=100(users),10(wheel),977(docker)
[mahmoud@madonna ~]$ $HOME
bash: /home/mahmoud: Is a directory
[mahmoud@madonna ~]$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4031288k,nr_inodes=1007822,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda1 on / type ext4 (rw,relatime,data=ordered)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14271)
systemd-1 on /home type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19418)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
/dev/sda2 on /var/log type ext4 (rw,relatime,data=ordered)
/dev/sda4 on /localhome type ext4 (rw,relatime,data=ordered)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
fsketzer:/data/project on /mnt/project type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=131.220.219.76,local_lock=none,addr=131.220.219.86)
fsketzer:/data/data on /mnt/data type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=131.220.219.76,local_lock=none,addr=131.220.219.86)
cbservice1.cb.uni-bonn.de:/home on /home type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=131.220.219.76,local_lock=none,addr=131.220.219.2)
tmpfs on /run/user/2142 type tmpfs (rw,nosuid,nodev,relatime,size=809488k,mode=700,uid=2142,gid=100)
gvfsd-fuse on /run/user/2142/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=2142,group_id=100)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
overlay on /var/lib/docker/overlay2/3115e1af76bda4c8dfd57afd857cd11ec026ed3f90a0f9c15d5670606f5a4196/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/JVGIWSDNDQQ4ENTBX4G636FT6M:/var/lib/docker/overlay2/l/LMA3BUNELD4TX7QGMVGHW2AEAG:/var/lib/docker/overlay2/l/HU3FUFASDUO4T5TZI56SFMAGQR:/var/lib/docker/overlay2/l/XASRYORRKDN2RC2GPVJVZT7ISM:/var/lib/docker/overlay2/l/RMCPFWJTQD36AS6ZMAK27S5NQQ,upperdir=/var/lib/docker/overlay2/3115e1af76bda4c8dfd57afd857cd11ec026ed3f90a0f9c15d5670606f5a4196/diff,workdir=/var/lib/docker/overlay2/3115e1af76bda4c8dfd57afd857cd11ec026ed3f90a0f9c15d5670606f5a4196/work)
shm on /var/lib/docker/containers/497a7c1d4563ada08f54c7ead2f3d94090e14100b1842abe642d585a34397760/mounts/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
proc on /run/docker/netns/ea3e2ecbab46 type proc (rw,nosuid,nodev,noexec,relatime)

**Comment by dberzano** [comment]
@tariqmahmoud running alidock on a network filesystem is not tested, and even if it worked... it's a bit suicidal, given the level of operations we need to perform.

This is the line relevant to your `/home` mount for reference:

```
systemd-1 on /home type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19418)
```

@mconcas: I believe that this can be solved by mounting `/home/alidock` with `shared`, however... do not use a network file system with alidock.

Do you have a local area you can use instead? I see a `/localhome` from your `mount` output. If this is the case, you can think of running alidock with:

```bash
alidock --shared /localhome/alidock
```

That is, assuming you have write permissions under `/localhome`. If this works, we'll explain how to make the setting permanent (i.e. without specifying `--shared` manually every time).

**Comment by tariqmahmoud** [comment]
alidock --shared /localhome/mahmoud/alidock
works.

with 
alias alidock='alidock --shared /localhome/mahmoud/alidock'
is even nicer ;-)
thanks @dberzano @mconcas

**Comment by dberzano** [comment]
OK so final try. Stop alidock:

```bash
alidock stop
```

Create, once for all, a config file named `~/.alidock-config.yaml` with the following content:

```yaml
---
dirOutside: /localhome/mahmoud/alidock
```

Test it without any parameter:

```bash
alidock
```

It should work out of the box! Can you confirm it does? Thanks!

**Comment by tariqmahmoud** [comment]
it works.

**Comment by mconcas** [comment]
Closing
