### ISSUE TITLE
Document configuration file

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#73]
alidock supports a configuration file, but this is not documented at the moment. Use cases described in #64 and #67 are better covered by using a configuration file.

**Comment by javierecc** [comment]
Hi, 
Sorry, by going trough the other issues it was not clear to me.
Is the mounting of cvmfs (on mac) working? The proposed --cvmfs flag is not yet in a release. Using a configuration file will work for that?
Thanks,
Javier

**Comment by mconcas** [comment]
Hi @javierecc ,
usually new features to the configuration and the `--xyz` flags goes together.
Yes, you are right, the upstream latest version does not have the `--cvmfs` option yet, changing configuration will not help, sorry.

We will publish it soon.

**Comment by dberzano** [comment]
Fixed in #138.
