### ISSUE TITLE
Alidock installation fails on linux

### ISSUE THREAD

**Issue by rqwa** [alidock/alidock#74]
When I try to install alidock I get the following error. The reason is a symlink from `/home/marco/.virtualenvs/alidock/lib64/python3.6/distutils/__init__.py` to `/usr/lib/python3.6/distutils/__init__py`.
This is a known problem for virtualenv 16.1.0 under linux see https://github.com/pypa/virtualenv/issues/1270.

```
> bash <(curl -fsSL https://bit.ly/alidock-installer)                                                  
Checking if your Docker installation works
Creating an environment for alidock using Python 3.6.6 (python3)
+ python3 pypa-virtualenv-4ad2742/src/virtualenv.py /home/marco/.virtualenvs/alidock
Using base prefix '/usr/lib/python-exec/python3.6/../../..'
New python executable in /home/marco/.virtualenvs/alidock/bin/python3
Also creating executable in /home/marco/.virtualenvs/alidock/bin/python
Overwriting /home/marco/.virtualenvs/alidock/lib64/python3.6/distutils/__init__.py with new content
Traceback (most recent call last):
  File "pypa-virtualenv-4ad2742/src/virtualenv.py", line 2462, in <module>
    main()
  File "pypa-virtualenv-4ad2742/src/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "pypa-virtualenv-4ad2742/src/virtualenv.py", line 1001, in create_environment
    install_distutils(home_dir)
  File "pypa-virtualenv-4ad2742/src/virtualenv.py", line 1580, in install_distutils
    writefile(os.path.join(distutils_path, "__init__.py"), DISTUTILS_INIT)
  File "pypa-virtualenv-4ad2742/src/virtualenv.py", line 431, in writefile
    with open(dest, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/home/marco/.virtualenvs/alidock/lib64/python3.6/distutils/__init__.py'
```

If I change the version to 16.0.0 I receive the following error.

```
> ./alidock-installer 
Checking if your Docker installation works
Creating an environment for alidock using Python 3.6.6 (python3)
+ python3 pypa-virtualenv-*/src/virtualenv.py /home/marco/.virtualenvs/alidock
/usr/lib/python-exec/python3.6/python3: can't open file 'pypa-virtualenv-*/src/virtualenv.py': [Errno 2] No such file or directory
```

There seems to be problem with the  tarball. In case of version 16.1.0 the identifier of the tarball is 4ad2742, which corresponds to the commit for 16.1.0 and agrees with the folder created in the temp directory (pypa-virtualenv-4ad27423cd7cfe). For 16.0.0 the identifier is 7a9a898, which agrees with the commit, but disagrees with the temp folder (pypa-virtualenv-3cd7cfe).

Changing virtualenv to 16.0.0 will probably break the compatibility to macOS.
A possible temporary solution could be to implement an OS dependent switch and change to version 16.0.0 for linux systems.
- [x] Detect OS
- [x] Download and run virtualenv 16.0.0

**Comment by dberzano** [comment]
I see why you can't open a PR 😄 So, what you say is that 16.0.0 works on Linux, but on macOS a newer version is required, right? An OS check would do IMHO for now.

**Comment by rqwa** [comment]
Using 16.0.0 is a suggested as workaround for linux, but currently I cannot test it, due to the second error.
The folder in the tar archive for 16.0.0 has different name compared to the tar file. This explains the different naming.

**Comment by dberzano** [comment]
@rqwa can you tell us more to help us reproducing the issue? What is your Linux distribution? Did you install a Python version of your own?

Given that this is a bug and we aim to fix it, you're not prevented from installing alidock by simply using `pip` if you want, in the meanwhile.

**Comment by dberzano** [comment]
Also: I see that version 16.2.0 is out, would it maybe fix the problem for everybody?

**Comment by dberzano** [comment]
@rqwa you can try the bash + curl command now to see if it works for you.

**Comment by rqwa** [comment]
bash + curl command still fails.
I run sabayon linux and only use the python version provided by the system, currently 3.6.
I tested it on our university system with centOS 7 and python2.7.5, where it worked as suggested.
There is a bug report about the same issue on ubuntu 18.04 in pypa/pipenv#3395.
The difference between the two systems is that on sabayon there is a symlink from `/home/marco/.virtualenvs/alidock/lib64/python3.6/distutils -> /usr/lib64/python3.6/distutils` while on centOS the distutils folder is no symlink.

**Comment by dberzano** [comment]
OK, I see. This is a problem that has to be solved on the virtualenv's side, somehow.

For me, I have just tried using 16.0.0 and it works, both on all my Linux versions and my latest macOS. Can you elaborate on your sentence:

> Changing virtualenv to 16.0.0 will probably break the compatibility to macOS.

It _seems_ to be working for me as said, but maybe I am overlooking something. Was this problem only related to the bad autodetection of `virtualenv.py` (which I fixed in #75)?

**Comment by rqwa** [comment]
> For me, I have just tried using 16.0.0 and it works, both on all my Linux versions and my latest macOS. Can you elaborate on your sentence:
> 
> > Changing virtualenv to 16.0.0 will probably break the compatibility to macOS.

The sentence comes from a comment, in the discussion of the virtualenv issue, where it is mentioned that the bug was introduced during a macOS fix. So I may over-interpreted it, sorry for that.

**Comment by dberzano** [comment]
I actually saw the comment after writing mine, sorry for overlooking it. I am changing the version conditionally, to be on the safe side.

**Comment by dberzano** [comment]
@rqwa can you try #76? It is sufficient do do:

```bash
bash <(curl -fsSl https://raw.githubusercontent.com/dberzano/alidock/pmub-virtualenv/alidock-installer.sh)
```

**Comment by rqwa** [comment]
> @rqwa can you try #76? It is sufficient do do:
> 
> ```shell
> bash <(curl -fsSl https://raw.githubusercontent.com/dberzano/alidock/pmub-virtualenv/alidock-installer.sh)
> ```

This works without problems.

**Comment by dberzano** [comment]
Merged upstream. You can install using the standard bash+curl command from the main page. Thanks for reporting and for your patience!
