### ISSUE TITLE
Error installing alidock on Linux

### ISSUE THREAD

**Issue by gluparel** [alidock/alidock#79]
Hello,

when I try to install alidock on Linux I get this error message:

~$ bash <(curl -fsSL https://bit.ly/alidock-installer)
Checking if your Docker installation works
Creating an environment for alidock using Python 3.6.7 (python3) and virtualenv 16.0.0
+ python3 pypa-virtualenv-3cd7cfe/virtualenv.py
/home/grazia/.virtualenvs/alidock
Traceback (most recent call last):
   File "pypa-virtualenv-3cd7cfe/virtualenv.py", line 25, in <module>
     import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'

Thanks
Cheers
Grazia

**Comment by dberzano** [comment]
Can you provide us with more information about your system? Is it Ubuntu 18.04? Are ALL of the OS updates installed?

Is the problem fixed by running:

```bash
sudo apt install python3-distutil
```

**Comment by gluparel** [comment]
Thanks a lot for the suggestion!
I am using Linux Mint 19.
Indeed the problem can be easily fixed by installing python3-distutils. 

I think that the issue can be closed. Many thanks again!

**Comment by dberzano** [comment]
Thanks for reporting.

@mconcas do you have any further comment on this issue? `python3-distutils` is, apparently, not installed by default on Ubuntu. Maybe we should perform some detection and warn the user when this happens?

Detection is as easy as `python -c 'import distutils'` for the record.
