### ISSUE TITLE
alidock docker error

### ISSUE THREAD

**Issue by fkellere** [alidock/alidock#83]
Hello,
when typing "alidock" for the first time after a seemingly successful installation, I got the following response:
Creating container, hold on
Docker error: 404 Client Error: Not Found ("no such image: alisw/alidock:latest: No such image: alisw/alidock:latest")
Some details: I have an earlier installation of aliBuild, I migrated the MIRROR to ~/alidock/.sw/. I am using linux with ubuntu. Could you please have a look? 
Thanks,
Fabian

**Comment by mconcas** [comment]
Hi Fabian,
could you please provide us some further information?
I am, in particular, interested in:
 - `docker info`
 - `alidock --version`
 - `cat $HOME/alidock/.alidock.log`

Thanks, and cheers

**Comment by fkellere** [comment]
docker info

Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 1
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 47GiB
Name: nx1
ID: JX4U:TGIM:HPR6:KZR7:2L5I:ZLPI:YBFS:IQV5:NTKC:5F4C:Y2EA:OS7Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by fkellere** [comment]
alidock --version

alidock 1.4.0

**Comment by fkellere** [comment]
$HOME/alidock/.alidock.log doesnt exist, however I have $HOME/alidock/.alidock-host.log, which just contains: "+ cd /"

**Comment by fkellere** [comment]
My bad, I'm of course using CentOS, not ubuntu

**Comment by mconcas** [comment]
What does `docker pull alisw/alidock:latest` return?

**Comment by fkellere** [comment]
latest: Pulling from alisw/alidock
aeb7866da422: Pull complete 
e0669f14a876: Extracting [==================================================>]  735.9MB/735.9MB
103196123059: Download complete 
d376032022b8: Download complete 
49802bb1911b: Download complete 
9f94c045fefe: Download complete 
058cf59c06ab: Download complete 
b7e1a50ec86d: Download complete 
failed to register layer: Error processing tar file(exit status 1): write /usr/src/kernels/3.10.0-862.14.4.el7.x86_64.debug/init/Makefile: no space left on device

**Comment by mconcas** [comment]
It looks like your disk is full.
What is the output of `df -h`?.
Can you try to free some space? 
Then please try again both `docker pull alisw/alidock:latest` and, if it succeeds, type `alidock`.
Please post output if it is not fixing.

**Comment by fkellere** [comment]
I am working on a remote SSH server, I should have around 29GB left on my quota. Its not that trivial to get more space if this is not enough but I will try and let you know.

**Comment by mconcas** [comment]
> Docker Root Dir: /var/lib/docker

It means that Docker is saving the images and the running containers on this system directory.
Most likely it is the system that is running out of memory, not your quota.
Can you please post the output of `df -h`?

**Comment by fkellere** [comment]
```
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/sda2                                   50G   33G   14G  71% /
devtmpfs                                    24G     0   24G   0% /dev
tmpfs                                       24G   12M   24G   1% /dev/shm
tmpfs                                       24G  859M   23G   4% /run
tmpfs                                       24G     0   24G   0% /sys/fs/cgroup
/dev/sda1                                  976M  386M  524M  43% /boot
/dev/sda5                                  9.8G   84M  9.2G   1% /tmp
/dev/sda6                                  9.8G  7.1G  2.2G  77% /var
/dev/sda7                                   55G   69M   52G   1% /var/tmp
nostromo.ktas.ph.tum.de:/scratch1           37T   36T  1.2T  97% /scratch1
nostromo.ktas.ph.tum.de:/scratch2           55T   48T  7.4T  87% /scratch2
cvmfs2                                      14G   56M   14G   1% /cvmfs/icecube.opensciencegrid.org
tuphzit-na3-nfs.ktas.ph.tum.de:/home/ktas  1.1T  990G   91G  92% /home
mother.ktas.ph.tum.de:/scratch4             37T   33T  3.6T  91% /scratch4
mother.ktas.ph.tum.de:/scratch3             37T   32T  4.5T  88% /scratch3
tmpfs                                      4.7G     0  4.7G   0% /run/user/2
animal.ktas.ph.tum.de:/scratch9             28T   24T  2.7T  90% /scratch9
sherpa.ktas.ph.tum.de:/scratch11            55T   22T   31T  42% /scratch11
valhalla.ktas.ph.tum.de:/scratch5           73T   19T   51T  27% /scratch5
valhalla.ktas.ph.tum.de:/scratch6           73T   15T   54T  22% /scratch6
ratatosk.ktas.ph.tum.de:/scratch7           73T  7.8T   62T  12% /scratch7
ratatosk.ktas.ph.tum.de:/scratch8           73T  471G   69T   1% /scratch8
sherpa.ktas.ph.tum.de:/scratch10            55T   44T  8.6T  84% /scratch10
tmpfs                                      4.7G  8.0K  4.7G   1% /run/user/3808644
tmpfs                                      4.7G  4.0K  4.7G   1% /run/user/3372627
tmpfs                                      4.7G     0  4.7G   0% /run/user/3214363
tmpfs                                      4.7G  4.0K  4.7G   1% /run/user/3166986
tmpfs                                      4.7G     0  4.7G   0% /run/user/3214204
tmpfs                                      4.7G  8.0K  4.7G   1% /run/user/3009016
tmpfs                                      4.7G     0  4.7G   0% /run/user/0
tmpfs                                      4.7G     0  4.7G   0% /run/user/3602833
```

**Comment by mconcas** [comment]
Ok, that could be the problem.
My advice is to contact the administrator of the server and ask for some space for your containers (10GB for `/var/`is going to saturate eventually very soon, if your docker is configured to work there... :sob: ).
The fully unpacked `alisw/alidock` image is 2.19GB but notice that Docker needs at least double of the space to unpack it, every time you pull it.

For the moment it does not look like something we can fix on our side, I am closing this now.
Please, don't hesitate to reopen it in case of some other issue with the `alidock` installation or malfunction.

Cheers,
Matteo Concas
