### ISSUE TITLE
Functional and unit tests

### ISSUE THREAD

**Issue by mconcas** [alidock/alidock#86]
For Linux, MacOS aaaand... Windows

**Comment by mconcas** [comment]
We want to test:
**Installation**
- [ ] Linux
- [ ] MacOS
- [ ] Win

**Commands**
 - [ ] `enter, root, exec, start, status, stop`
 - [ ] Management by name (more than one container running)

**Configuration param & conf-file**
 - [ ] Custom image
 - [ ] External mounts
 - [ ] CVMFS
 - [ ] Configuration override

**Coverage**
 - [ ] CodeCov :question:

**Hardcore Tests  :skull_and_crossbones:**
 - [ ] nvidia runtime
 - [ ] X11 forwarding

**Comment by dberzano** [comment]
Coverage. Let's not forget coverage!

**Comment by samperumal** [comment]
Is there a specific unit testing framework you intend using?

**Comment by mconcas** [comment]
Hi @samperumal , 
we didn't discuss it yet. We have some options, coming from previous know-how.
If you have any suggestion, it is welcome to be considered.

Cheers

**Comment by samperumal** [comment]
I don't have any experience with Python Unit testing specifically (I'm more in the C# space), so I'm happy to follow your lead. My dev platform at the moment is docker on windows, so happy to contribute in that space where I can.

**Comment by dberzano** [comment]
Let's add some ingredients:

* Run some OS-specific functional tests on Docker on Travis
* Expose the Travis Docker socket inside our container
* Run unit tests as well by mocking the Docker API and the call to SSH
