### ISSUE TITLE
Windows specific path issues

### ISSUE THREAD

**Issue by samperumal** [alidock/alidock#93]
Following #78 I've been using AliDock on Docker for Windows quite successfully (thanks for this!), but have also encountered a couple issues related to paths, specifically:

 * The --mount flag uses os.path.join to create the internal mount point in the container, when it should be using posixpath.
 * The .yaml config file path gets confused between forward and back slashes when expanding "~/.alidock-config.yaml" on windows. 

Both issues are provisionally fixed in PR #92.

This is my first time contributing, so please let me know if there are additional things I need to do prior to approval.

**Comment by dberzano** [comment]
Thanks! We've accepted your PR.
